#!/bin/sh
#
# bootstrap
#

set -e

#
# Check for Bundler
#
if test ! $(which bundle)
then
    echo "  x You need to install Bundler:"
    echo "    gem install bundler"
    exit
else
    echo "  + Bundler found."
fi

#
# Install gems
#
echo "  + Bootstrapping your Rubies."
bundle install --binstubs --path vendor/gems

#
# Install puppet modules
#
echo "  + install to ./modules"
bundle exec librarian-puppet install
